// Generated by gencpp from file fiona_pkg/Application_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_APPLICATION_SRV_H
#define FIONA_PKG_MESSAGE_APPLICATION_SRV_H

#include <ros/service_traits.h>


#include <Application_srvRequest.h>
#include <Application_srvResponse.h>


namespace fiona_pkg
{

struct Application_srv
{

typedef Application_srvRequest Request;
typedef Application_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Application_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::Application_srv > {
  static const char* value()
  {
    return "39aa4ad1a24b9c26be3b0379bac64358";
  }

  static const char* value(const ::fiona_pkg::Application_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::Application_srv > {
  static const char* value()
  {
    return "fiona_pkg/Application_srv";
  }

  static const char* value(const ::fiona_pkg::Application_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::Application_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::Application_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Application_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Application_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Application_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Application_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::Application_srv > 
template<>
struct DataType< ::fiona_pkg::Application_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Application_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Application_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::Application_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::Application_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Application_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Application_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Application_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Application_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::Application_srv > 
template<>
struct DataType< ::fiona_pkg::Application_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Application_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Application_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_APPLICATION_SRV_H
