// Generated by gencpp from file fiona_pkg/FrameEventSubscriber_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_FRAMEEVENTSUBSCRIBER_SRV_H
#define FIONA_PKG_MESSAGE_FRAMEEVENTSUBSCRIBER_SRV_H

#include <ros/service_traits.h>


#include "FrameEventSubscriber_srvRequest.h"
#include "FrameEventSubscriber_srvResponse.h"


namespace fiona_pkg
{

struct FrameEventSubscriber_srv
{

typedef FrameEventSubscriber_srvRequest Request;
typedef FrameEventSubscriber_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FrameEventSubscriber_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::FrameEventSubscriber_srv > {
  static const char* value()
  {
    return "54867ad3e1feaa0a42c33377d31476aa";
  }

  static const char* value(const ::fiona_pkg::FrameEventSubscriber_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::FrameEventSubscriber_srv > {
  static const char* value()
  {
    return "fiona_pkg/FrameEventSubscriber_srv";
  }

  static const char* value(const ::fiona_pkg::FrameEventSubscriber_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::FrameEventSubscriber_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::FrameEventSubscriber_srv > 
template<>
struct MD5Sum< ::fiona_pkg::FrameEventSubscriber_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::FrameEventSubscriber_srv >::value();
  }
  static const char* value(const ::fiona_pkg::FrameEventSubscriber_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::FrameEventSubscriber_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::FrameEventSubscriber_srv > 
template<>
struct DataType< ::fiona_pkg::FrameEventSubscriber_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::FrameEventSubscriber_srv >::value();
  }
  static const char* value(const ::fiona_pkg::FrameEventSubscriber_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::FrameEventSubscriber_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::FrameEventSubscriber_srv > 
template<>
struct MD5Sum< ::fiona_pkg::FrameEventSubscriber_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::FrameEventSubscriber_srv >::value();
  }
  static const char* value(const ::fiona_pkg::FrameEventSubscriber_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::FrameEventSubscriber_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::FrameEventSubscriber_srv > 
template<>
struct DataType< ::fiona_pkg::FrameEventSubscriber_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::FrameEventSubscriber_srv >::value();
  }
  static const char* value(const ::fiona_pkg::FrameEventSubscriber_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_FRAMEEVENTSUBSCRIBER_SRV_H
