// Generated by gencpp from file fiona_pkg/CameraPosition_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_CAMERAPOSITION_SRV_H
#define FIONA_PKG_MESSAGE_CAMERAPOSITION_SRV_H

#include <ros/service_traits.h>


#include "CameraPosition_srvRequest.h"
#include "CameraPosition_srvResponse.h"


namespace fiona_pkg
{

struct CameraPosition_srv
{

typedef CameraPosition_srvRequest Request;
typedef CameraPosition_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraPosition_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::CameraPosition_srv > {
  static const char* value()
  {
    return "680a62b912db8e5cb344b00d1458d2ec";
  }

  static const char* value(const ::fiona_pkg::CameraPosition_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::CameraPosition_srv > {
  static const char* value()
  {
    return "fiona_pkg/CameraPosition_srv";
  }

  static const char* value(const ::fiona_pkg::CameraPosition_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::CameraPosition_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::CameraPosition_srv > 
template<>
struct MD5Sum< ::fiona_pkg::CameraPosition_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::CameraPosition_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraPosition_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::CameraPosition_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::CameraPosition_srv > 
template<>
struct DataType< ::fiona_pkg::CameraPosition_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::CameraPosition_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraPosition_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::CameraPosition_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::CameraPosition_srv > 
template<>
struct MD5Sum< ::fiona_pkg::CameraPosition_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::CameraPosition_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraPosition_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::CameraPosition_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::CameraPosition_srv > 
template<>
struct DataType< ::fiona_pkg::CameraPosition_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::CameraPosition_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraPosition_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_CAMERAPOSITION_SRV_H
