// Generated by gencpp from file fiona_pkg/CameraParameters_srvRequest.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_CAMERAPARAMETERS_SRVREQUEST_H
#define FIONA_PKG_MESSAGE_CAMERAPARAMETERS_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fiona_pkg
{
template <class ContainerAllocator>
struct CameraParameters_srvRequest_
{
  typedef CameraParameters_srvRequest_<ContainerAllocator> Type;

  CameraParameters_srvRequest_()
    : IsOrtho(false)
    , VisionAngle(0.0)
    , nearClippingPlane(0.0)
    , FarClippingPlane(0.0)  {
    }
  CameraParameters_srvRequest_(const ContainerAllocator& _alloc)
    : IsOrtho(false)
    , VisionAngle(0.0)
    , nearClippingPlane(0.0)
    , FarClippingPlane(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _IsOrtho_type;
  _IsOrtho_type IsOrtho;

   typedef float _VisionAngle_type;
  _VisionAngle_type VisionAngle;

   typedef float _nearClippingPlane_type;
  _nearClippingPlane_type nearClippingPlane;

   typedef float _FarClippingPlane_type;
  _FarClippingPlane_type FarClippingPlane;





  typedef boost::shared_ptr< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraParameters_srvRequest_

typedef ::fiona_pkg::CameraParameters_srvRequest_<std::allocator<void> > CameraParameters_srvRequest;

typedef boost::shared_ptr< ::fiona_pkg::CameraParameters_srvRequest > CameraParameters_srvRequestPtr;
typedef boost::shared_ptr< ::fiona_pkg::CameraParameters_srvRequest const> CameraParameters_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fiona_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'fiona_pkg': ['/home/blade/catkin_ws/src/fiona_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c01ac40f7cd385db73a226cbc8df6f9";
  }

  static const char* value(const ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c01ac40f7cd385dULL;
  static const uint64_t static_value2 = 0xb73a226cbc8df6f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fiona_pkg/CameraParameters_srvRequest";
  }

  static const char* value(const ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool IsOrtho\n"
"float32 VisionAngle\n"
"float32 nearClippingPlane\n"
"float32 FarClippingPlane\n"
;
  }

  static const char* value(const ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.IsOrtho);
      stream.next(m.VisionAngle);
      stream.next(m.nearClippingPlane);
      stream.next(m.FarClippingPlane);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraParameters_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fiona_pkg::CameraParameters_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "IsOrtho: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.IsOrtho);
    s << indent << "VisionAngle: ";
    Printer<float>::stream(s, indent + "  ", v.VisionAngle);
    s << indent << "nearClippingPlane: ";
    Printer<float>::stream(s, indent + "  ", v.nearClippingPlane);
    s << indent << "FarClippingPlane: ";
    Printer<float>::stream(s, indent + "  ", v.FarClippingPlane);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIONA_PKG_MESSAGE_CAMERAPARAMETERS_SRVREQUEST_H
