// Generated by gencpp from file fiona_pkg/CameraParameters_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_CAMERAPARAMETERS_SRV_H
#define FIONA_PKG_MESSAGE_CAMERAPARAMETERS_SRV_H

#include <ros/service_traits.h>


#include "CameraParameters_srvRequest.h"
#include "CameraParameters_srvResponse.h"


namespace fiona_pkg
{

struct CameraParameters_srv
{

typedef CameraParameters_srvRequest Request;
typedef CameraParameters_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraParameters_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::CameraParameters_srv > {
  static const char* value()
  {
    return "4be5de60894d6a34505e51790fd9fb5d";
  }

  static const char* value(const ::fiona_pkg::CameraParameters_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::CameraParameters_srv > {
  static const char* value()
  {
    return "fiona_pkg/CameraParameters_srv";
  }

  static const char* value(const ::fiona_pkg::CameraParameters_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::CameraParameters_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::CameraParameters_srv > 
template<>
struct MD5Sum< ::fiona_pkg::CameraParameters_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::CameraParameters_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraParameters_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::CameraParameters_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::CameraParameters_srv > 
template<>
struct DataType< ::fiona_pkg::CameraParameters_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::CameraParameters_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraParameters_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::CameraParameters_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::CameraParameters_srv > 
template<>
struct MD5Sum< ::fiona_pkg::CameraParameters_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::CameraParameters_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraParameters_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::CameraParameters_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::CameraParameters_srv > 
template<>
struct DataType< ::fiona_pkg::CameraParameters_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::CameraParameters_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraParameters_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_CAMERAPARAMETERS_SRV_H
