// Generated by gencpp from file fiona_pkg/CameraRotation_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_CAMERAROTATION_SRV_H
#define FIONA_PKG_MESSAGE_CAMERAROTATION_SRV_H

#include <ros/service_traits.h>


#include "CameraRotation_srvRequest.h"
#include "CameraRotation_srvResponse.h"


namespace fiona_pkg
{

struct CameraRotation_srv
{

typedef CameraRotation_srvRequest Request;
typedef CameraRotation_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraRotation_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::CameraRotation_srv > {
  static const char* value()
  {
    return "85d566839c2d54e6a5674c968e25c902";
  }

  static const char* value(const ::fiona_pkg::CameraRotation_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::CameraRotation_srv > {
  static const char* value()
  {
    return "fiona_pkg/CameraRotation_srv";
  }

  static const char* value(const ::fiona_pkg::CameraRotation_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::CameraRotation_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::CameraRotation_srv > 
template<>
struct MD5Sum< ::fiona_pkg::CameraRotation_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::CameraRotation_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraRotation_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::CameraRotation_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::CameraRotation_srv > 
template<>
struct DataType< ::fiona_pkg::CameraRotation_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::CameraRotation_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraRotation_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::CameraRotation_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::CameraRotation_srv > 
template<>
struct MD5Sum< ::fiona_pkg::CameraRotation_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::CameraRotation_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraRotation_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::CameraRotation_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::CameraRotation_srv > 
template<>
struct DataType< ::fiona_pkg::CameraRotation_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::CameraRotation_srv >::value();
  }
  static const char* value(const ::fiona_pkg::CameraRotation_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_CAMERAROTATION_SRV_H
