// Generated by gencpp from file fiona_pkg/Renderizable_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_RENDERIZABLE_SRV_H
#define FIONA_PKG_MESSAGE_RENDERIZABLE_SRV_H

#include <ros/service_traits.h>


#include "Renderizable_srvRequest.h"
#include "Renderizable_srvResponse.h"


namespace fiona_pkg
{

struct Renderizable_srv
{

typedef Renderizable_srvRequest Request;
typedef Renderizable_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Renderizable_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::Renderizable_srv > {
  static const char* value()
  {
    return "f88ead5ccb009add1f78db7b89849e0d";
  }

  static const char* value(const ::fiona_pkg::Renderizable_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::Renderizable_srv > {
  static const char* value()
  {
    return "fiona_pkg/Renderizable_srv";
  }

  static const char* value(const ::fiona_pkg::Renderizable_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::Renderizable_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::Renderizable_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Renderizable_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Renderizable_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Renderizable_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Renderizable_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::Renderizable_srv > 
template<>
struct DataType< ::fiona_pkg::Renderizable_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Renderizable_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Renderizable_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::Renderizable_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::Renderizable_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Renderizable_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Renderizable_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Renderizable_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Renderizable_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::Renderizable_srv > 
template<>
struct DataType< ::fiona_pkg::Renderizable_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Renderizable_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Renderizable_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_RENDERIZABLE_SRV_H
