// Generated by gencpp from file fiona_pkg/AsyncFatalErrorHandler_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_ASYNCFATALERRORHANDLER_SRV_H
#define FIONA_PKG_MESSAGE_ASYNCFATALERRORHANDLER_SRV_H

#include <ros/service_traits.h>


#include <AsyncFatalErrorHandler_srvRequest.h>
#include <AsyncFatalErrorHandler_srvResponse.h>


namespace fiona_pkg
{

struct AsyncFatalErrorHandler_srv
{

typedef AsyncFatalErrorHandler_srvRequest Request;
typedef AsyncFatalErrorHandler_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AsyncFatalErrorHandler_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::AsyncFatalErrorHandler_srv > {
  static const char* value()
  {
    return "9effcea74600cb8e05e12f97948c06db";
  }

  static const char* value(const ::fiona_pkg::AsyncFatalErrorHandler_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::AsyncFatalErrorHandler_srv > {
  static const char* value()
  {
    return "fiona_pkg/AsyncFatalErrorHandler_srv";
  }

  static const char* value(const ::fiona_pkg::AsyncFatalErrorHandler_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::AsyncFatalErrorHandler_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::AsyncFatalErrorHandler_srv > 
template<>
struct MD5Sum< ::fiona_pkg::AsyncFatalErrorHandler_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::AsyncFatalErrorHandler_srv >::value();
  }
  static const char* value(const ::fiona_pkg::AsyncFatalErrorHandler_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::AsyncFatalErrorHandler_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::AsyncFatalErrorHandler_srv > 
template<>
struct DataType< ::fiona_pkg::AsyncFatalErrorHandler_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::AsyncFatalErrorHandler_srv >::value();
  }
  static const char* value(const ::fiona_pkg::AsyncFatalErrorHandler_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::AsyncFatalErrorHandler_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::AsyncFatalErrorHandler_srv > 
template<>
struct MD5Sum< ::fiona_pkg::AsyncFatalErrorHandler_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::AsyncFatalErrorHandler_srv >::value();
  }
  static const char* value(const ::fiona_pkg::AsyncFatalErrorHandler_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::AsyncFatalErrorHandler_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::AsyncFatalErrorHandler_srv > 
template<>
struct DataType< ::fiona_pkg::AsyncFatalErrorHandler_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::AsyncFatalErrorHandler_srv >::value();
  }
  static const char* value(const ::fiona_pkg::AsyncFatalErrorHandler_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_ASYNCFATALERRORHANDLER_SRV_H
