// Generated by gencpp from file fiona_pkg/Concurrent_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_CONCURRENT_SRV_H
#define FIONA_PKG_MESSAGE_CONCURRENT_SRV_H

#include <ros/service_traits.h>


#include "Concurrent_srvRequest.h"
#include "Concurrent_srvResponse.h"


namespace fiona_pkg
{

struct Concurrent_srv
{

typedef Concurrent_srvRequest Request;
typedef Concurrent_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Concurrent_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::Concurrent_srv > {
  static const char* value()
  {
    return "ac814f2457854af8ad23b07274ee6bf0";
  }

  static const char* value(const ::fiona_pkg::Concurrent_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::Concurrent_srv > {
  static const char* value()
  {
    return "fiona_pkg/Concurrent_srv";
  }

  static const char* value(const ::fiona_pkg::Concurrent_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::Concurrent_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::Concurrent_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Concurrent_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Concurrent_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Concurrent_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Concurrent_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::Concurrent_srv > 
template<>
struct DataType< ::fiona_pkg::Concurrent_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Concurrent_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Concurrent_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::Concurrent_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::Concurrent_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Concurrent_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Concurrent_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Concurrent_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Concurrent_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::Concurrent_srv > 
template<>
struct DataType< ::fiona_pkg::Concurrent_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Concurrent_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Concurrent_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_CONCURRENT_SRV_H
