// Generated by gencpp from file fiona_pkg/Eyes_srvRequest.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_EYES_SRVREQUEST_H
#define FIONA_PKG_MESSAGE_EYES_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fiona_pkg
{
template <class ContainerAllocator>
struct Eyes_srvRequest_
{
  typedef Eyes_srvRequest_<ContainerAllocator> Type;

  Eyes_srvRequest_()
    : pan(0.0)
    , tilt(0.0)  {
    }
  Eyes_srvRequest_(const ContainerAllocator& _alloc)
    : pan(0.0)
    , tilt(0.0)  {
  (void)_alloc;
    }



   typedef float _pan_type;
  _pan_type pan;

   typedef float _tilt_type;
  _tilt_type tilt;





  typedef boost::shared_ptr< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Eyes_srvRequest_

typedef ::fiona_pkg::Eyes_srvRequest_<std::allocator<void> > Eyes_srvRequest;

typedef boost::shared_ptr< ::fiona_pkg::Eyes_srvRequest > Eyes_srvRequestPtr;
typedef boost::shared_ptr< ::fiona_pkg::Eyes_srvRequest const> Eyes_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fiona_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'fiona_pkg': ['/home/blade/catkin_ws/src/fiona_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938e11f380abc0513a5b7367d0f157bf";
  }

  static const char* value(const ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938e11f380abc051ULL;
  static const uint64_t static_value2 = 0x3a5b7367d0f157bfULL;
};

template<class ContainerAllocator>
struct DataType< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fiona_pkg/Eyes_srvRequest";
  }

  static const char* value(const ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pan\n"
"float32 tilt\n"
;
  }

  static const char* value(const ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan);
      stream.next(m.tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Eyes_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fiona_pkg::Eyes_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIONA_PKG_MESSAGE_EYES_SRVREQUEST_H
