// Generated by gencpp from file fiona_pkg/Eyes_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_EYES_SRV_H
#define FIONA_PKG_MESSAGE_EYES_SRV_H

#include <ros/service_traits.h>


#include "Eyes_srvRequest.h"
#include "Eyes_srvResponse.h"


namespace fiona_pkg
{

struct Eyes_srv
{

typedef Eyes_srvRequest Request;
typedef Eyes_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Eyes_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::Eyes_srv > {
  static const char* value()
  {
    return "e7261bc9ed42e73f40f14d718070557e";
  }

  static const char* value(const ::fiona_pkg::Eyes_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::Eyes_srv > {
  static const char* value()
  {
    return "fiona_pkg/Eyes_srv";
  }

  static const char* value(const ::fiona_pkg::Eyes_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::Eyes_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::Eyes_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Eyes_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Eyes_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Eyes_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Eyes_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::Eyes_srv > 
template<>
struct DataType< ::fiona_pkg::Eyes_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Eyes_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Eyes_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::Eyes_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::Eyes_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Eyes_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Eyes_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Eyes_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Eyes_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::Eyes_srv > 
template<>
struct DataType< ::fiona_pkg::Eyes_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Eyes_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Eyes_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_EYES_SRV_H
