// Generated by gencpp from file fiona_pkg/Animation_srvRequest.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_ANIMATION_SRVREQUEST_H
#define FIONA_PKG_MESSAGE_ANIMATION_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fiona_pkg
{
template <class ContainerAllocator>
struct Animation_srvRequest_
{
  typedef Animation_srvRequest_<ContainerAllocator> Type;

  Animation_srvRequest_()
    : avatarFilename()  {
    }
  Animation_srvRequest_(const ContainerAllocator& _alloc)
    : avatarFilename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _avatarFilename_type;
  _avatarFilename_type avatarFilename;





  typedef boost::shared_ptr< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Animation_srvRequest_

typedef ::fiona_pkg::Animation_srvRequest_<std::allocator<void> > Animation_srvRequest;

typedef boost::shared_ptr< ::fiona_pkg::Animation_srvRequest > Animation_srvRequestPtr;
typedef boost::shared_ptr< ::fiona_pkg::Animation_srvRequest const> Animation_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fiona_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'fiona_pkg': ['/home/blade/catkin_ws/src/fiona_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2089fbc754391c13278876318fc4f9e6";
  }

  static const char* value(const ::fiona_pkg::Animation_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2089fbc754391c13ULL;
  static const uint64_t static_value2 = 0x278876318fc4f9e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fiona_pkg/Animation_srvRequest";
  }

  static const char* value(const ::fiona_pkg::Animation_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string avatarFilename\n"
;
  }

  static const char* value(const ::fiona_pkg::Animation_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.avatarFilename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Animation_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fiona_pkg::Animation_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fiona_pkg::Animation_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "avatarFilename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.avatarFilename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIONA_PKG_MESSAGE_ANIMATION_SRVREQUEST_H
