// Generated by gencpp from file fiona_pkg/DetectedFacePositionConsumer_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_DETECTEDFACEPOSITIONCONSUMER_SRV_H
#define FIONA_PKG_MESSAGE_DETECTEDFACEPOSITIONCONSUMER_SRV_H

#include <ros/service_traits.h>


#include "DetectedFacePositionConsumer_srvRequest.h"
#include "DetectedFacePositionConsumer_srvResponse.h"


namespace fiona_pkg
{

struct DetectedFacePositionConsumer_srv
{

typedef DetectedFacePositionConsumer_srvRequest Request;
typedef DetectedFacePositionConsumer_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectedFacePositionConsumer_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::DetectedFacePositionConsumer_srv > {
  static const char* value()
  {
    return "38a3b0ff3ac6901bee07e2f94e96c43c";
  }

  static const char* value(const ::fiona_pkg::DetectedFacePositionConsumer_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::DetectedFacePositionConsumer_srv > {
  static const char* value()
  {
    return "fiona_pkg/DetectedFacePositionConsumer_srv";
  }

  static const char* value(const ::fiona_pkg::DetectedFacePositionConsumer_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::DetectedFacePositionConsumer_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::DetectedFacePositionConsumer_srv > 
template<>
struct MD5Sum< ::fiona_pkg::DetectedFacePositionConsumer_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::DetectedFacePositionConsumer_srv >::value();
  }
  static const char* value(const ::fiona_pkg::DetectedFacePositionConsumer_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::DetectedFacePositionConsumer_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::DetectedFacePositionConsumer_srv > 
template<>
struct DataType< ::fiona_pkg::DetectedFacePositionConsumer_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::DetectedFacePositionConsumer_srv >::value();
  }
  static const char* value(const ::fiona_pkg::DetectedFacePositionConsumer_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::DetectedFacePositionConsumer_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::DetectedFacePositionConsumer_srv > 
template<>
struct MD5Sum< ::fiona_pkg::DetectedFacePositionConsumer_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::DetectedFacePositionConsumer_srv >::value();
  }
  static const char* value(const ::fiona_pkg::DetectedFacePositionConsumer_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::DetectedFacePositionConsumer_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::DetectedFacePositionConsumer_srv > 
template<>
struct DataType< ::fiona_pkg::DetectedFacePositionConsumer_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::DetectedFacePositionConsumer_srv >::value();
  }
  static const char* value(const ::fiona_pkg::DetectedFacePositionConsumer_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_DETECTEDFACEPOSITIONCONSUMER_SRV_H
