// Generated by gencpp from file fiona_pkg/VoiceSay_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_VOICESAY_SRV_H
#define FIONA_PKG_MESSAGE_VOICESAY_SRV_H

#include <ros/service_traits.h>


#include "VoiceSay_srvRequest.h"
#include "VoiceSay_srvResponse.h"


namespace fiona_pkg
{

struct VoiceSay_srv
{

typedef VoiceSay_srvRequest Request;
typedef VoiceSay_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VoiceSay_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::VoiceSay_srv > {
  static const char* value()
  {
    return "c4034f444716fbaf8eb933a3ce02d1c4";
  }

  static const char* value(const ::fiona_pkg::VoiceSay_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::VoiceSay_srv > {
  static const char* value()
  {
    return "fiona_pkg/VoiceSay_srv";
  }

  static const char* value(const ::fiona_pkg::VoiceSay_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::VoiceSay_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::VoiceSay_srv > 
template<>
struct MD5Sum< ::fiona_pkg::VoiceSay_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::VoiceSay_srv >::value();
  }
  static const char* value(const ::fiona_pkg::VoiceSay_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::VoiceSay_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::VoiceSay_srv > 
template<>
struct DataType< ::fiona_pkg::VoiceSay_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::VoiceSay_srv >::value();
  }
  static const char* value(const ::fiona_pkg::VoiceSay_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::VoiceSay_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::VoiceSay_srv > 
template<>
struct MD5Sum< ::fiona_pkg::VoiceSay_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::VoiceSay_srv >::value();
  }
  static const char* value(const ::fiona_pkg::VoiceSay_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::VoiceSay_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::VoiceSay_srv > 
template<>
struct DataType< ::fiona_pkg::VoiceSay_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::VoiceSay_srv >::value();
  }
  static const char* value(const ::fiona_pkg::VoiceSay_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_VOICESAY_SRV_H
