// Generated by gencpp from file fiona_pkg/VoiceWaitStop_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_VOICEWAITSTOP_SRV_H
#define FIONA_PKG_MESSAGE_VOICEWAITSTOP_SRV_H

#include <ros/service_traits.h>


#include "VoiceWaitStop_srvRequest.h"
#include "VoiceWaitStop_srvResponse.h"


namespace fiona_pkg
{

struct VoiceWaitStop_srv
{

typedef VoiceWaitStop_srvRequest Request;
typedef VoiceWaitStop_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VoiceWaitStop_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::VoiceWaitStop_srv > {
  static const char* value()
  {
    return "0fad1ffea84185a805f4b5b880fb8d64";
  }

  static const char* value(const ::fiona_pkg::VoiceWaitStop_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::VoiceWaitStop_srv > {
  static const char* value()
  {
    return "fiona_pkg/VoiceWaitStop_srv";
  }

  static const char* value(const ::fiona_pkg::VoiceWaitStop_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::VoiceWaitStop_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::VoiceWaitStop_srv > 
template<>
struct MD5Sum< ::fiona_pkg::VoiceWaitStop_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::VoiceWaitStop_srv >::value();
  }
  static const char* value(const ::fiona_pkg::VoiceWaitStop_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::VoiceWaitStop_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::VoiceWaitStop_srv > 
template<>
struct DataType< ::fiona_pkg::VoiceWaitStop_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::VoiceWaitStop_srv >::value();
  }
  static const char* value(const ::fiona_pkg::VoiceWaitStop_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::VoiceWaitStop_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::VoiceWaitStop_srv > 
template<>
struct MD5Sum< ::fiona_pkg::VoiceWaitStop_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::VoiceWaitStop_srv >::value();
  }
  static const char* value(const ::fiona_pkg::VoiceWaitStop_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::VoiceWaitStop_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::VoiceWaitStop_srv > 
template<>
struct DataType< ::fiona_pkg::VoiceWaitStop_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::VoiceWaitStop_srv >::value();
  }
  static const char* value(const ::fiona_pkg::VoiceWaitStop_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_VOICEWAITSTOP_SRV_H
