// Generated by gencpp from file fiona_pkg/FaceExpression_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_FACEEXPRESSION_SRV_H
#define FIONA_PKG_MESSAGE_FACEEXPRESSION_SRV_H

#include <ros/service_traits.h>


#include "FaceExpression_srvRequest.h"
#include "FaceExpression_srvResponse.h"


namespace fiona_pkg
{

struct FaceExpression_srv
{

typedef FaceExpression_srvRequest Request;
typedef FaceExpression_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaceExpression_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::FaceExpression_srv > {
  static const char* value()
  {
    return "b74e5db62f0be0d5dd949ad8cd8a14cf";
  }

  static const char* value(const ::fiona_pkg::FaceExpression_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::FaceExpression_srv > {
  static const char* value()
  {
    return "fiona_pkg/FaceExpression_srv";
  }

  static const char* value(const ::fiona_pkg::FaceExpression_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::FaceExpression_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::FaceExpression_srv > 
template<>
struct MD5Sum< ::fiona_pkg::FaceExpression_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::FaceExpression_srv >::value();
  }
  static const char* value(const ::fiona_pkg::FaceExpression_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::FaceExpression_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::FaceExpression_srv > 
template<>
struct DataType< ::fiona_pkg::FaceExpression_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::FaceExpression_srv >::value();
  }
  static const char* value(const ::fiona_pkg::FaceExpression_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::FaceExpression_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::FaceExpression_srv > 
template<>
struct MD5Sum< ::fiona_pkg::FaceExpression_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::FaceExpression_srv >::value();
  }
  static const char* value(const ::fiona_pkg::FaceExpression_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::FaceExpression_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::FaceExpression_srv > 
template<>
struct DataType< ::fiona_pkg::FaceExpression_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::FaceExpression_srv >::value();
  }
  static const char* value(const ::fiona_pkg::FaceExpression_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_FACEEXPRESSION_SRV_H
