// Generated by gencpp from file fiona_pkg/ControlVoice_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_CONTROLVOICE_SRV_H
#define FIONA_PKG_MESSAGE_CONTROLVOICE_SRV_H

#include <ros/service_traits.h>


#include "ControlVoice_srvRequest.h"
#include "ControlVoice_srvResponse.h"


namespace fiona_pkg
{

struct ControlVoice_srv
{

typedef ControlVoice_srvRequest Request;
typedef ControlVoice_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlVoice_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::ControlVoice_srv > {
  static const char* value()
  {
    return "eef2bbea74a2c8b560f63ed0fa429d93";
  }

  static const char* value(const ::fiona_pkg::ControlVoice_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::ControlVoice_srv > {
  static const char* value()
  {
    return "fiona_pkg/ControlVoice_srv";
  }

  static const char* value(const ::fiona_pkg::ControlVoice_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::ControlVoice_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::ControlVoice_srv > 
template<>
struct MD5Sum< ::fiona_pkg::ControlVoice_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::ControlVoice_srv >::value();
  }
  static const char* value(const ::fiona_pkg::ControlVoice_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::ControlVoice_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::ControlVoice_srv > 
template<>
struct DataType< ::fiona_pkg::ControlVoice_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::ControlVoice_srv >::value();
  }
  static const char* value(const ::fiona_pkg::ControlVoice_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::ControlVoice_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::ControlVoice_srv > 
template<>
struct MD5Sum< ::fiona_pkg::ControlVoice_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::ControlVoice_srv >::value();
  }
  static const char* value(const ::fiona_pkg::ControlVoice_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::ControlVoice_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::ControlVoice_srv > 
template<>
struct DataType< ::fiona_pkg::ControlVoice_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::ControlVoice_srv >::value();
  }
  static const char* value(const ::fiona_pkg::ControlVoice_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_CONTROLVOICE_SRV_H
