// Generated by gencpp from file fiona_pkg/AudioSize_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_AUDIOSIZE_SRV_H
#define FIONA_PKG_MESSAGE_AUDIOSIZE_SRV_H

#include <ros/service_traits.h>


#include "AudioSize_srvRequest.h"
#include "AudioSize_srvResponse.h"


namespace fiona_pkg
{

struct AudioSize_srv
{

typedef AudioSize_srvRequest Request;
typedef AudioSize_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AudioSize_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::AudioSize_srv > {
  static const char* value()
  {
    return "6e204a5418d344637ae7c404c23d6002";
  }

  static const char* value(const ::fiona_pkg::AudioSize_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::AudioSize_srv > {
  static const char* value()
  {
    return "fiona_pkg/AudioSize_srv";
  }

  static const char* value(const ::fiona_pkg::AudioSize_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::AudioSize_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::AudioSize_srv > 
template<>
struct MD5Sum< ::fiona_pkg::AudioSize_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::AudioSize_srv >::value();
  }
  static const char* value(const ::fiona_pkg::AudioSize_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::AudioSize_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::AudioSize_srv > 
template<>
struct DataType< ::fiona_pkg::AudioSize_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::AudioSize_srv >::value();
  }
  static const char* value(const ::fiona_pkg::AudioSize_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::AudioSize_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::AudioSize_srv > 
template<>
struct MD5Sum< ::fiona_pkg::AudioSize_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::AudioSize_srv >::value();
  }
  static const char* value(const ::fiona_pkg::AudioSize_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::AudioSize_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::AudioSize_srv > 
template<>
struct DataType< ::fiona_pkg::AudioSize_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::AudioSize_srv >::value();
  }
  static const char* value(const ::fiona_pkg::AudioSize_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_AUDIOSIZE_SRV_H
