// Generated by gencpp from file fiona_pkg/Neck_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_NECK_SRV_H
#define FIONA_PKG_MESSAGE_NECK_SRV_H

#include <ros/service_traits.h>


#include "Neck_srvRequest.h"
#include "Neck_srvResponse.h"


namespace fiona_pkg
{

struct Neck_srv
{

typedef Neck_srvRequest Request;
typedef Neck_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Neck_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::Neck_srv > {
  static const char* value()
  {
    return "19dccaa126d0f010e689d4e5ab232068";
  }

  static const char* value(const ::fiona_pkg::Neck_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::Neck_srv > {
  static const char* value()
  {
    return "fiona_pkg/Neck_srv";
  }

  static const char* value(const ::fiona_pkg::Neck_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::Neck_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::Neck_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Neck_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Neck_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Neck_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Neck_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::Neck_srv > 
template<>
struct DataType< ::fiona_pkg::Neck_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Neck_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Neck_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::Neck_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::Neck_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Neck_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Neck_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Neck_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Neck_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::Neck_srv > 
template<>
struct DataType< ::fiona_pkg::Neck_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Neck_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Neck_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_NECK_SRV_H
