// Generated by gencpp from file fiona_pkg/WindowColorDepth_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_WINDOWCOLORDEPTH_SRV_H
#define FIONA_PKG_MESSAGE_WINDOWCOLORDEPTH_SRV_H

#include <ros/service_traits.h>


#include "WindowColorDepth_srvRequest.h"
#include "WindowColorDepth_srvResponse.h"


namespace fiona_pkg
{

struct WindowColorDepth_srv
{

typedef WindowColorDepth_srvRequest Request;
typedef WindowColorDepth_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WindowColorDepth_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::WindowColorDepth_srv > {
  static const char* value()
  {
    return "2055bb65cfd29c9dc4c0e2f1761b4f24";
  }

  static const char* value(const ::fiona_pkg::WindowColorDepth_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::WindowColorDepth_srv > {
  static const char* value()
  {
    return "fiona_pkg/WindowColorDepth_srv";
  }

  static const char* value(const ::fiona_pkg::WindowColorDepth_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::WindowColorDepth_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::WindowColorDepth_srv > 
template<>
struct MD5Sum< ::fiona_pkg::WindowColorDepth_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::WindowColorDepth_srv >::value();
  }
  static const char* value(const ::fiona_pkg::WindowColorDepth_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::WindowColorDepth_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::WindowColorDepth_srv > 
template<>
struct DataType< ::fiona_pkg::WindowColorDepth_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::WindowColorDepth_srv >::value();
  }
  static const char* value(const ::fiona_pkg::WindowColorDepth_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::WindowColorDepth_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::WindowColorDepth_srv > 
template<>
struct MD5Sum< ::fiona_pkg::WindowColorDepth_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::WindowColorDepth_srv >::value();
  }
  static const char* value(const ::fiona_pkg::WindowColorDepth_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::WindowColorDepth_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::WindowColorDepth_srv > 
template<>
struct DataType< ::fiona_pkg::WindowColorDepth_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::WindowColorDepth_srv >::value();
  }
  static const char* value(const ::fiona_pkg::WindowColorDepth_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_WINDOWCOLORDEPTH_SRV_H
