// Generated by gencpp from file fiona_pkg/Window_srv.msg
// DO NOT EDIT!


#ifndef FIONA_PKG_MESSAGE_WINDOW_SRV_H
#define FIONA_PKG_MESSAGE_WINDOW_SRV_H

#include <ros/service_traits.h>


#include "Window_srvRequest.h"
#include "Window_srvResponse.h"


namespace fiona_pkg
{

struct Window_srv
{

typedef Window_srvRequest Request;
typedef Window_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Window_srv
} // namespace fiona_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiona_pkg::Window_srv > {
  static const char* value()
  {
    return "7bf1ba6dc460c14d473f5d8e3979a77e";
  }

  static const char* value(const ::fiona_pkg::Window_srv&) { return value(); }
};

template<>
struct DataType< ::fiona_pkg::Window_srv > {
  static const char* value()
  {
    return "fiona_pkg/Window_srv";
  }

  static const char* value(const ::fiona_pkg::Window_srv&) { return value(); }
};


// service_traits::MD5Sum< ::fiona_pkg::Window_srvRequest> should match 
// service_traits::MD5Sum< ::fiona_pkg::Window_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Window_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Window_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Window_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Window_srvRequest> should match 
// service_traits::DataType< ::fiona_pkg::Window_srv > 
template<>
struct DataType< ::fiona_pkg::Window_srvRequest>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Window_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Window_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiona_pkg::Window_srvResponse> should match 
// service_traits::MD5Sum< ::fiona_pkg::Window_srv > 
template<>
struct MD5Sum< ::fiona_pkg::Window_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiona_pkg::Window_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Window_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiona_pkg::Window_srvResponse> should match 
// service_traits::DataType< ::fiona_pkg::Window_srv > 
template<>
struct DataType< ::fiona_pkg::Window_srvResponse>
{
  static const char* value()
  {
    return DataType< ::fiona_pkg::Window_srv >::value();
  }
  static const char* value(const ::fiona_pkg::Window_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIONA_PKG_MESSAGE_WINDOW_SRV_H
